### ISSUE TITLE
[Feature Request] Super Sonic

### ISSUE THREAD

**Issue by KarmaIsLame** [DS-GAMING-SE/Sonic#3]
A great feature would be to add Super Sonic a some sort of transformation that allows the user to fly for example. Maybe a different moveset taking advantage of Sonic's other moves in Frontiers (I.E Wild Rush, Loop Kick, etc...).Would be pretty sick!

**Comment by DxsSucuk** [comment]
Agree, would be great to see super sonic be part of the mod!

**Comment by DxsSucuk** [comment]
https://github.com/DS-GAMING-SE/Sonic/pull/4

**Comment by DxsSucuk** [comment]
@DS-GAMING-SE Shouldn't this Issue be closed since he has already been added and enabled?

**Comment by lolkitre123** [comment]
@DxsSucuk This is actually in the mod?

**Comment by DxsSucuk** [comment]
Yes @lolkitre123 it has been inside for a long time, I made a PR around Sep 2023 where I readded the stuff DS commented out. But since then DS has put in the effort to balance it and make it functional compared to the PR I made. And with the 2.0.0 release he just published, Super Sonic is now out there!
